# Generated by Django 3.2.19 on 2023-06-22 05:45

import MyPlantApp.my_plant.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, validators=[django.core.validators.MaxLengthValidator(2)])),
                ('first_name', models.CharField(max_length=20, validators=[MyPlantApp.my_plant.validators.validate_profile_names])),
                ('last_name', models.CharField(max_length=20, validators=[MyPlantApp.my_plant.validators.validate_profile_names])),
                ('profile_picture', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
